package slicer

import (
	"bytes"
	"image/color"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestEncodeColPicProducesData(t *testing.T) {
	img := renderThumbnail([]triangle3{{
		a: point3{x: 0, y: 0, z: 0},
		b: point3{x: 10, y: 0, z: 0},
		c: point3{x: 0, y: 10, z: 10},
	}}, 32, neptune4Background())

	encoded := encodeColPic(img)
	if encoded == "" {
		t.Fatal("expected encoded COLPIC data")
	}
	if strings.Contains(encoded, "\\") {
		t.Fatal("COLPIC output must escape backslash as tilde")
	}
}

func TestAddNeptune4ThumbnailsToGCode(t *testing.T) {
	dir := t.TempDir()
	gcodePath := filepath.Join(dir, "out.gcode")
	if err := os.WriteFile(gcodePath, []byte("; generated by test\nG28\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	if err := addNeptune4ThumbnailsToGCode(gcodePath, testASCIISTL()); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(gcodePath)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(data, []byte(";gimage:")) || !bytes.Contains(data, []byte(";simage:")) {
		t.Fatalf("expected COLPIC thumbnail blocks, got %q", string(data[:min(len(data), 80)]))
	}
	if !bytes.Contains(data, []byte("G28")) {
		t.Fatal("expected original G-code to be preserved")
	}
}

func neptune4Background() color.RGBA {
	return color.RGBA{R: 0x30, G: 0x39, B: 0x4f, A: 0xff}
}

func testASCIISTL() []byte {
	return []byte(`solid test
facet normal 0 0 1
outer loop
vertex 0 0 0
vertex 20 0 0
vertex 0 20 20
endloop
endfacet
endsolid test`)
}
